### ISSUE TITLE
WhiteHouse.gov Drupal launch

### ISSUE THREAD

**Issue by mglaman** [weitzman/drupal-timeline#2]
I know it's WordPress now, but it'd be cool to highlight that the White House used Drupal – and the We the People petition platform.

**Comment by weitzman** [comment]
Yes, very worthy. PR welcome.

**Comment by weitzman** [comment]
https://dri.es/whitehouse-gov-using-drupal

**Comment by mglaman** [comment]
Fixed by https://github.com/weitzman/drupal-timeline/commit/fa55bc19ebf02fdfaed145a8725fd031bf12408f
