### ISSUE TITLE
What to do about images?

### ISSUE THREAD

**Issue by bmann** [weitzman/drupal-timeline#28]
And more broadly, markdown in the description :)

There are some Dries album links, I debated including an `images: ["full-http-link-to-image", "another-image"]` array, but probably easier to just stick a couple in the description for now?

**Comment by weitzman** [comment]
Yeah, I think Markdown in description makes a lot of sense. And I think we should add a new `thumbnail` field. Additional images can go in the body as needed.

**Comment by weitzman** [comment]
We now accept a single image in a 'thumbnail' property. I could use help populating this for many entries ... FYI Markdown is now used as well.
