### ISSUE TITLE
Experiment: Jekyll site that generates JSON

### ISSUE THREAD

**Issue by bmann** [weitzman/drupal-timeline#29]
I've built a couple of these JSON plain text sites now. I've found that letting people enter markdown, and then generating a JSON feed with Jekyll / GitHub Pages means you get an always correct feed.

I'm going to do an example in my fork and report back here with an example.

Also: there's a formula I saw floating around of creating committed markdown posts from Issues. So -- anyone could create an issue, and when approved, it can get merged in, without having to do an entire git flow. So that might be experiment 2

**Comment by bmann** [comment]
OK, I have a branch: https://github.com/bmann/drupal-timeline/tree/bmann-jekyll

This should build on GH Pages no problem.

I've done a publish here: https://drupal-timeline.fission.app/

Direct link to the generated JSON: https://drupal-timeline.fission.app/api/timeline.json

**Comment by weitzman** [comment]
Great idea. You've made the first visualization! Dunno how much work you want to put into it, but it would be cool if it looked like Open Atrium or Goofy theme. When you are ready, lets add this link to the README.

FYI your generated JSON is getting confused by commas in the description, leading to invalid JSON.

Is it deliberate that there are only 3 posts on the site, and no descriptions?

Thanks for running with this project. This is just the spirit I'm hoping to tap into!

**Comment by bmann** [comment]
Yeah it was getting late. I need to tweak the excerpt / filtering there. 

To be clear: I’m suggesting using markdown as the default format for posts so people don’t need to hand type / make PRs of raw JSON.

Made some notes in the source. Can create different types of feeds for easier visualization. Eg TimelineJS https://timeline.knightlab.com/docs/json-format.html
