### ISSUE TITLE
add entry for d10 release

### ISSUE THREAD

**Issue by arysom** [weitzman/drupal-timeline#46]
14 december https://www.drupal10party.com/

**Comment by weitzman** [comment]
Good idea! Hopefully someone can come up with some text to describe D10.

**Comment by dan2k3k4** [comment]
The text from the About section seems OK?

> Over twenty years in the making, Drupal 10 is the latest and greatest version of the Drupal content management system. Powering sites such as NASA, Tesla, and millions more, Drupal is a high powered, low-code CMS with a large and devoted developer community.

**Comment by weitzman** [comment]
Lets make it about D10 specifically. Like key new features.

**Comment by arysom** [comment]
Drupal 10.0.0 released

Claro administration theme and Olivero default theme, the introduction of CKEditor 5, further jQuery replacements, theme starterkit tools for theme creation, and Symfony 6 under the hood with PHP 8.1 requirement.

**Comment by weitzman** [comment]
fixed in https://github.com/weitzman/drupal-timeline/pull/47
